#!/bin/bash

function copy {
  [ ! -f "$sync_file" ] && error "---> No $sync_file file in current directory" false && exit 1

  msg "Copying files" false
  for file in $(cat $sync_file); do
    file=$(echo $file | sed "s@~@$HOME@")
    local currtarget=$target$(echo $file | sed "s@$HOME@@")
    local currtargetdir=${target%/*}

    [ ! -d $currtargetdir ] && mkdir -p $currtargetdir
    if [ -f $file ]; then
      cp $file $currtarget && echo $file "sync'd to" $currtarget
      [ $? -ne 0 ] && error "$file FAILED to sync" false
    else
      cp $file $currtargetdir && echo $file "sync'd to" $currtarget
      [ $? -ne 0 ] && error "$file FAILED to sync" false
    fi
  done
}

function commit {
  msg "Committing to $branch_name" true

  inFile .git/info/exclude $sync_file
  [ $? -eq 0 ] && echo "$sync_file" >> .git/info/exclude
  [ $? -eq 0 ] && msg "Added $sync_file to .git/info/exclude"

  git add -A || exit 1
  git commit || msg "Nothing to commit" false
}

function push {
  msg "Updating remote status" true
  git remote update
  if [ $(git status  -uno | grep ahead | grep $branch_name | wc -l) -ge 1 ]; then
    msg "Pushing to remote" true
    git push || exit 1
  fi

  msg "Done!" false
}

function showhelp {
cat << HERE
Usage syncdt [OPTION]..
  -c Commit to current git branch
  -p Push to remote
  -a Add file to sync to the sync.files file
  -f Specify the file with the list of files and directories to be synced
  -t Specity the target directory
HERE
exit 0
}

function inFile {
  [ ! -f $1 ] && return 0
  for line in $(cat $1); do
    [ $line = "$2" ] && return 1
  done
  return 0
}

function msg {
  $2 && echo
  echo -e "\033[34;1m--->  $1\033[0m"
}

function error {
  $2 && echo
  echo -e "\033[31;1m$1\033[0m"
}

function add {
  inFile $sync_file $1 && echo $1 >> $sync_file
}

function setfile {
  sync_file=$1
}

function settarget {
  target=$1
}

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" || branch_name="(unnamed branch)"
branch_name=${branch_name##refs/heads/}

sync_file=sync.files
target=$PWD
cmd=none

for arg in $@; do
  if [ ${arg:0:1} != '-' ]; then
    funcs+=("$cmd $arg")
    continue
  fi
  case $arg in
    -c)
      funcs+=("commit")
      ;;
    -p)
      funcs+=("push")
      ;;
    -cp)
      funcs+=("commit")
      funcs+=("push")
      ;;
    -pc)
      funcs+=("commit")
      funcs+=("push")
      ;;
    -a)
      cmd=add
      ;;
    -f)
      cmd=setfile
      ;;
    -t)
      cmd=settarget
      ;;
    -h)
      showhelp
      ;;
    --help)
      showhelp
      ;;
  esac
done

for i in ${!funcs[@]}; do
  case ${funcs[$i]} in
    setfile*)
      ${funcs[$i]}
      break
      ;;
  esac
done
for i in ${!funcs[@]}; do
  case ${funcs[$i]} in
    settarget*)
      ${funcs[$i]}
      break
      ;;
  esac
done
for i in ${!funcs[@]}; do
  case ${funcs[$i]} in
    add*)
      ${funcs[$i]}
      ;;
  esac
done

copy

for i in ${!funcs[@]}; do
  [ "${funcs[$i]}" = "commit" ] && commit && break
done
for i in ${!funcs[@]}; do
  [ "${funcs[$i]}" = "push" ] && push && break
done

exit 0
